### ISSUE TITLE
ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by hssgtest** [MaartenGr/BERTopic#107]
In a use case where some of the documents have only few words, the clustering often throws the following exception:

`Traceback (most recent call last):
  File "main.py", line 26, in <module>
    topics, _ = topic_model.fit_transform(docs)
  File "/usr/local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 287, in fit_transform
    self._extract_topics(documents)
  File "/usr/local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1146, in _extract_topics
    self.topics = self._extract_words_per_topic(words)
  File "/usr/local/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1269, in _extract_words_per_topic
    topic_words = mmr(topic_embedding, word_embeddings, words, top_n=self.top_n_words, diversity=0)
  File "/usr/local/lib/python3.8/site-packages/bertopic/_mmr.py", line 47, in mmr
    mmr_idx = candidates_idx[np.argmax(mmr)]
  File "<__array_function__ internals>", line 5, in argmax
  File "/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1193, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence`
 
The file main.py and the set of documents and the parameters are attached to reproduce the error. 
[BertTopic-Exception.zip](https://github.com/MaartenGr/BERTopic/files/6391088/BertTopic-Exception.zip)

**Comment by hssgtest** [comment]
![image](https://user-images.githubusercontent.com/22390899/116389730-9313d300-a81d-11eb-872d-297e78019f9d.png)

**Comment by MaartenGr** [comment]
It seems to be caused by the number of documents you are passing to BERTopic. 33 documents is not enough to create a good topic model and it seems that there are too little words in the dictionary to create enough candidates for MMR. In practice, I would advise you to use at leat a few hundred documents that each contains at least a sentence or multiple words.
