### ISSUE TITLE
ValueError with approximate_distribution()

### ISSUE THREAD

**Issue by devanshrj** [MaartenGr/BERTopic#1094]
Hi, thank you for this awesome work!

I am using BERTopic to generate topics and document-topic distribution on a corpus containing 4.4M tweets. I ran into memory issues with `fit()`, so I am now using online topic modeling with `partial_fit()`. My model trains successfully and I am able to get top n words for each topic, but I run into a `ValueError: Input contains NaN, infinity or a value too large for dtype('float64').` when I try to approximate document-topic distribution using `approximate_distribution()`.

Here's the code I used:
```python
data_df = pd.read_csv("corpus.tsv", sep='\t', names=['message', 'partition', 'label'])
corpus_li = data_df['message'].astype(str).to_list()
doc_chunks = [corpus_li[i:i+10000] for i in range(0, len(corpus_li), 10000)]
labels_li = data_df['label'].to_list()

sentence_model = SentenceTransformer(model, cache_folder=cache_path)
umap_model = IncrementalPCA(n_components=5)
cluster_model = MiniBatchKMeans(n_clusters=num_topics, random_state=0)
vectorizer_model = OnlineCountVectorizer(stop_words=None, decay=.01)

topic_model = BERTopic(
    nr_topics=num_topics,
    language=language,
    top_n_words=top_n_words,
    min_topic_size=min_topic_size,
    embedding_model=sentence_model,
    umap_model=umap_model,
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    n_gram_range=(1, 1),
    low_memory=True,
    calculate_probabilities=False,
    seed_topic_list=None,
    ctfidf_model=None,
    verbose=True,
)

topic_words = topic_model.get_topics()

doc_topic_m, _ = topic_model.approximate_distribution(corpus_li, batch_size=10000)
```

Here's the traceback:
```
Traceback (most recent call last):
  File "/nlp/data/devansh/topic_model/prediction/bertopic_old.py", line 115, in <module>
    doc_topic_m, _ = topic_model.approximate_distribution(corpus_li, batch_size=10000)
  File "/nlp/data/devansh/conda_envs/lib/python3.7/site-packages/bertopic/_bertopic.py", line 1114, in approximate_distribution
    similarity = cosine_similarity(c_tf_idf_doc, self.c_tf_idf_[self._outliers:])
  File "/nlp/data/devansh/conda_envs/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 1251, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/nlp/data/devansh/conda_envs/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 170, in check_pairwise_arrays
    estimator=estimator,
  File "/nlp/data/devansh/conda_envs/lib/python3.7/site-packages/sklearn/utils/validation.py", line 726, in check_array
    accept_large_sparse=accept_large_sparse,
  File "/nlp/data/devansh/conda_envs/lib/python3.7/site-packages/sklearn/utils/validation.py", line 479, in _ensure_sparse_format
    _assert_all_finite(spmatrix.data, allow_nan=force_all_finite == "allow-nan")
  File "/nlp/data/devansh/conda_envs/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by MaartenGr** [comment]
Just to be sure, the code that you provided is fully complete? The reason why I ask is that I am missing the `.partial_fit` function here.

**Comment by devanshrj** [comment]
I forgot to mention that line, apologies for the confusion!

Here's the code again:
```python
data_df = pd.read_csv("corpus.tsv", sep='\t', names=['message', 'partition', 'label'])
corpus_li = data_df['message'].astype(str).to_list()
doc_chunks = [corpus_li[i:i+10000] for i in range(0, len(corpus_li), 10000)]
labels_li = data_df['label'].to_list()

sentence_model = SentenceTransformer(model, cache_folder=cache_path)
umap_model = IncrementalPCA(n_components=5)
cluster_model = MiniBatchKMeans(n_clusters=num_topics, random_state=0)
vectorizer_model = OnlineCountVectorizer(stop_words=None, decay=.01)

topic_model = BERTopic(
    nr_topics=num_topics,
    language=language,
    top_n_words=top_n_words,
    min_topic_size=min_topic_size,
    embedding_model=sentence_model,
    umap_model=umap_model,
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    n_gram_range=(1, 1),
    low_memory=True,
    calculate_probabilities=False,
    seed_topic_list=None,
    ctfidf_model=None,
    verbose=True,
)

for i, docs in enumerate(doc_chunks):
    print(f"Training on chunk {i+1} of {len(doc_chunks)}")
    topic_model.partial_fit(docs)

topic_words = topic_model.get_topics()

doc_topic_m, _ = topic_model.approximate_distribution(corpus_li, batch_size=10000)
```

**Comment by MaartenGr** [comment]
I am not entirely sure but it might be a result of the `decay` factor when running `.partial_fit`. It seems that values are generated that either contain NaN of infinity because of that. Could you check if `topic_model.c_tf_idf_` contains any of those values?

**Comment by jburdo1** [comment]
I think you are spot on there Maarten, I am seeing the same behavior with the `decay` argument.

**Comment by devanshrj** [comment]
Sorry for the delay! Maarten, I checked the values contained in `topic_model.c_tf_idf_`, and they all seem to be tending toward NaN. Do you have any suggestions on how I could tweak the `decay` factor to prevent this?

**Comment by MaartenGr** [comment]
@devanshrj I would suggest either not using `decay` at all or setting it to a very small value like `1e-5`. That way, the decay is more suited to the frequency of calling `.partial_fit` and the number of documents that are passed with each fit.

**Comment by MaartenGr** [comment]
Closing this due to inactivity. Let me know if I need to re-open the issue!
