### ISSUE TITLE
BERTopic install fails due to numba not supporting Python 3.11

### ISSUE THREAD

**Issue by HaakonME** [MaartenGr/BERTopic#1216]
Hi Maarten,

It seems 'pip install bertopic' fails due to numba not supporting Python 3.11, see error message below. Do you know of a way round this, save waiting for numba for 3.11?

```
Collecting numba>=0.49 (from umap-learn>=0.5.0->bertopic)
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\myuser\AppData\Local\Temp\pip-install-x86a7ofj\numba_53a2fd1350f0447fae128349abec7fec\setup.py", line 51, in <module>
      _guard_py_ver()
    File "C:\Users\myuser\AppData\Local\Temp\pip-install-x86a7ofj\numba_53a2fd1350f0447fae128349abec7fec\setup.py", line 48, in _guard_py_ver
      raise RuntimeError(msg.format(cur_py, min_py, max_py))
  RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

​```

**Comment by MaartenGr** [comment]
From what I can remember, the UMAP package is at least one of the dependencies that have Numba as a requirement which is also a hard requirement for BERTopic. Unfortunately, this means that you will have to wait until Numba supports python 3.11.

**Comment by HaakonME** [comment]
Thanks, Maartin! If I really have to, I can do a parallell install in its own environment.
