### ISSUE TITLE
AttributeError: Can't get attribute '_make_function' on <module 'numba.cloudpickle.cloudpickle'>

### ISSUE THREAD

**Issue by zhimin-z** [MaartenGr/BERTopic#1236]
```
(.venv) 21zz42@docjk-gpu-01:~/Asset-Management-Topic-Modeling$ python Code/best_model.py
Traceback (most recent call last):
  File "/home/21zz42/Asset-Management-Topic-Modeling/Code/best_model.py", line 35, in <module>
    topic_model = BERTopic.load(os.path.join(path_model, model_name))
  File "/home/21zz42/Asset-Management-Topic-Modeling/.venv/lib/python3.10/site-packages/bertopic/_bertopic.py", line 2781, in load
    topic_model = joblib.load(file)
  File "/home/21zz42/Asset-Management-Topic-Modeling/.venv/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 648, in load
    obj = _unpickle(fobj)
  File "/home/21zz42/Asset-Management-Topic-Modeling/.venv/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.10/pickle.py", line 1590, in load_reduce
    stack[-1] = func(*args)
  File "/home/21zz42/Asset-Management-Topic-Modeling/.venv/lib/python3.10/site-packages/numba/core/serialize.py", line 97, in _unpickle__CustomPickled
    ctor, states = loads(serialized)
AttributeError: Can't get attribute '_make_function' on <module 'numba.cloudpickle.cloudpickle' from '/home/21zz42/Asset-Management-Topic-Modeling/.venv/lib/python3.10/site-packages/numba/cloudpickle/cloudpickle.py'>
```
When I am loading the Bertopic model, it crashes....

**Comment by MaartenGr** [comment]
Could you provide a bit more context? As in, could you share your full code for creating the model and saving the model? Also, did you make sure that the two environments are **exactly** the same? Typically, if loading a BERTopic model does not work then the environments differ.

**Comment by MaartenGr** [comment]
Could you also share the package versions of BERTopic, its dependencies and python of both environments?

**Comment by zhimin-z** [comment]
`bertopic==0.14.1`
`Python==3.10.*`
Full code:
```
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models.coherencemodel import CoherenceModel
from bertopic.vectorizers import ClassTfidfTransformer
from sentence_transformers import SentenceTransformer
from bertopic.representation import KeyBERTInspired
from bertopic import BERTopic
from hdbscan import HDBSCAN
from umap import UMAP

import gensim.corpora as corpora
import pandas as pd
import wandb
import os

path_result = 'Result'
path_dataset = 'Dataset'

path_general = os.path.join(path_result, 'General')

path_model = os.path.join(path_general, 'Model')
if not os.path.exists(path_model):
    os.makedirs(path_model)

wandb_project = 'asset-management-topic-modeling'

os.environ["TOKENIZERS_PARALLELISM"] = "true"
os.environ["WANDB__SERVICE_WAIT"] = "100"

# set default sweep configuration
config_defaults = {
    # Refer to https://www.sbert.net/docs/pretrained_models.html
    'model_name': 'all-MiniLM-L6-v2',
    'metric_distane': 'manhattan',
    'calculate_probabilities': True,
    'reduce_frequent_words': True,
    'prediction_data': True,
    'low_memory': False,
    'min_cluster_size': 50,
    'random_state': 42,
    'n_components': 5,
    'ngram_range': 2
}

config_sweep = {
    "method": "grid",
    "metric": {
        'name': 'Coherence CV',
        'goal': 'maximize'
    },
    "parameters": {
        'min_samples': {
            'values': list(range(1, config_defaults['min_cluster_size'] + 1))
        },
    },
}


class TopicModeling:
    def __init__(self, docs_name):
        # Initialize an empty list to store top models
        self.top_models = []
        self.path_model = path_model

        df = pd.read_json(os.path.join(path_dataset, 'preprocessed.json'))
        challenge = 'Challenge_' + docs_name
        solution = 'Solution_' + docs_name
        docs_challenge = df[df[challenge].notna()][challenge].tolist()
        docs_solution = df[df[solution].notna()][solution].tolist()
        self.docs = docs_challenge + docs_solution
        
        config_sweep['name'] = docs_name
        self.sweep_defaults = config_sweep

    def __train(self):
        # Initialize a new wandb run
        with wandb.init() as run:
            # update any values not set by sweep
            run.config.setdefaults(config_defaults)

            # Step 1 - Extract embeddings
            embedding_model = SentenceTransformer(run.config.model_name)

            # Step 2 - Reduce dimensionality
            umap_model = UMAP(n_components=run.config.n_components, metric=run.config.metric_distane,
                              random_state=run.config.random_state, low_memory=run.config.low_memory)

            # Step 3 - Cluster reduced embeddings
            hdbscan_model = HDBSCAN(min_cluster_size=run.config.min_cluster_size,
                                    min_samples=wandb.config.min_samples, prediction_data=run.config.prediction_data)

            # Step 4 - Tokenize topics
            vectorizer_model = TfidfVectorizer(ngram_range=(1, run.config.ngram_range))

            # Step 5 - Create topic representation
            ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=run.config.reduce_frequent_words)

            # Step 6 - Fine-tune topic representation
            representation_model = KeyBERTInspired()

            # All steps together
            topic_model = BERTopic(
                embedding_model=embedding_model,
                umap_model=umap_model,
                hdbscan_model=hdbscan_model,
                vectorizer_model=vectorizer_model,
                ctfidf_model=ctfidf_model,
                representation_model=representation_model,
                calculate_probabilities=run.config.calculate_probabilities
            )

            topics, _ = topic_model.fit_transform(self.docs)

            # Preprocess Documents
            documents = pd.DataFrame({"Document": self.docs,
                                      "ID": range(len(self.docs)),
                                      "Topic": topics})
            documents_per_topic = documents.groupby(
                ['Topic'], as_index=False).agg({'Document': ' '.join})
            cleaned_docs = topic_model._preprocess_text(
                documents_per_topic.Document.values)

            # Extract vectorizer and analyzer from BERTopic
            vectorizer = topic_model.vectorizer_model
            analyzer = vectorizer.build_analyzer()

            # Extract features for Topic Coherence evaluation
            tokens = [analyzer(doc) for doc in cleaned_docs]
            dictionary = corpora.Dictionary(tokens)
            corpus = [dictionary.doc2bow(token) for token in tokens]
            topic_words = [[words for words, _ in topic_model.get_topic(
                topic)] for topic in range(len(set(topics))-1)]

            coherence_cv = CoherenceModel(
                topics=topic_words,
                texts=tokens,
                corpus=corpus,
                dictionary=dictionary,
                coherence='c_v'
            )

            coherence_umass = CoherenceModel(
                topics=topic_words,
                texts=tokens,
                corpus=corpus,
                dictionary=dictionary,
                coherence='u_mass'
            )

            coherence_cuci = CoherenceModel(
                topics=topic_words,
                texts=tokens,
                corpus=corpus,
                dictionary=dictionary,
                coherence='c_uci'
            )

            coherence_cnpmi = CoherenceModel(
                topics=topic_words,
                texts=tokens,
                corpus=corpus,
                dictionary=dictionary,
                coherence='c_npmi'
            )

            coherence_cv = coherence_cv.get_coherence()
            wandb.log({'Coherence CV': coherence_cv})
            wandb.log({'Coherence UMASS': coherence_umass.get_coherence()})
            wandb.log({'Coherence UCI': coherence_cuci.get_coherence()})
            wandb.log({'Coherence NPMI': coherence_cnpmi.get_coherence()})
            number_topics = topic_model.get_topic_info().shape[0] - 1
            wandb.log({'Topic Number': number_topics})
            wandb.log(
                {'Uncategorized Post Number': topic_model.get_topic_info().at[0, 'Count']})

            # persist top 5 topic models

            model_name = f'{self.sweep_defaults["name"]}_{run.id}'
            model = {
                'model_path': os.path.join(self.path_model, model_name),
                'model_metrics': {
                    'number_topics': number_topics,
                    'coherence_cv': coherence_cv,
                }
            }
            
            # Inspect the new model only the topic number is above 20 
            if number_topics > 20:
                # Add the new model to the list if model number is below 5
                if len(self.top_models) < 5:
                    self.top_models.append(model)
                    topic_model.save(model['model_path'])
                else:
                    # Find the model with the lowest topic number in the list
                    lowest_number_topics_model = min(
                        self.top_models, key=lambda x: x['model_metrics']['number_topics'])
                    lowest_number_topics = lowest_number_topics_model['model_metrics']['number_topics']
                    if coherence_cv > lowest_number_topics_model['model_metrics']['coherence_cv']:
                        # Replace the model with the lowest topic number in the list with the new model
                        self.top_models.remove(lowest_number_topics_model)
                        os.remove(lowest_number_topics_model['model_path'])
                        self.top_models.append(model)
                        topic_model.save(model['model_path'])

    def sweep(self):
        wandb.login()
        sweep_id = wandb.sweep(self.sweep_defaults, project=wandb_project)
        wandb.agent(sweep_id, function=self.__train)
```

**Comment by zhimin-z** [comment]
Similar to this one:https://github.com/MaartenGr/BERTopic/issues/266

**Comment by MaartenGr** [comment]
Strange, if the environments are the same, with the same package versions for all packages (including numba, numpy, hdbscan, umap, etc.) then it should not give such an error. 

It might be worthwhile to start from a completely fresh environment, install BERTopic there and try to save and load a minimal example. Based on your code, it does not seem there is anything stopping from successfully saving and loading a BERTopic since it is currently nothing more than a `joblib.dump`. 

Also, perhaps something is going on with newer versions of dependencies that might be updated recently. Which versions of numba, numpy, hdbscan, umap, transformer, pytorch and sentence-transformers do you have?

**Comment by zhimin-z** [comment]
I am using docker for all the experimentation, here is my requirements.txt:
```
bertopic==0.14.1
gensim==4.3.1
kaleido==0.2.1
matplotlib==3.7.1
missingno==0.5.2
openai==0.27.6
plotly==5.14.1
seaborn==0.12.2
shap==0.41.0
statsmodels==0.13.5
textstat==0.7.3
wandb==0.15.0
wordcloud==1.9.1.1
xgboost==1.7.5
```
Anything special?

**Comment by MaartenGr** [comment]
That's tricky. The only thing that I can think of is that although you are using docker, the versions of numba, numpy, hdbscan, umap, etc. are not pinned. Looking back at the latest releases of [numba](https://github.com/numba/numba/releases/) and [numpy](https://github.com/numpy/numpy/releases), it seems that they have been updated relatively recently. That means that they might have been updated between you saving the model and loading it which would explain why you get an error loading the model.

**Comment by MaartenGr** [comment]
Closing this due to inactivity. Let me know if I need to re-open the issue!
