### ISSUE TITLE
Use BERTopic().transform() when model was trained with Online Topic Modeling approach

### ISSUE THREAD

**Issue by JRatschat** [MaartenGr/BERTopic#1297]
Hi, I want to use the BERTopic model in inference mode (BERTopic().transform()) after training it with the Online Topic Modeling approach stated [here](https://maartengr.github.io/BERTopic/getting_started/online/online.html).

Additionally to the tutorial which can be found in the official documentation, I load the trained model and try to apply it on the same documents with 

```
# Load topic model
topic_model = BERTopic.load("models/train_model")

# Inference
topic_model.transform(docs)
```

Unfortunately, the code breaks at `topic_model.transform(docs)` with the following error: `AttributeError: 'River' object has no attribute 'predict'`.

I tried to add a transform function to the River class but this approach led to the same error message. Any help or ideas are very welcome. Thanks so much in advance!

Here you can find a reproducible example:

```
import pandas as pd
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer, OnlineCountVectorizer
from datasets import load_dataset
from river import cluster, stream


# Load dataset
dataset = load_dataset("banking77")
docs = pd.DataFrame(dataset["train"])["text"].head(100).tolist()


class River:
    def __init__(self, model):
        self.model = model

    def partial_fit(self, umap_embeddings):
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            self.model = self.model.learn_one(umap_embedding)

        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            labels.append(label)

        self.labels_ = labels
        return self

# Using DBSTREAM to detect new topics as they come in
cluster_model = River(cluster.DBSTREAM())
vectorizer_model = OnlineCountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)

# Prepare model
topic_model = BERTopic(
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
)

# Train model
topic_model.partial_fit(docs)

# Save topic model
topic_model.save("models/train_model")

# Load topic model
topic_model = BERTopic.load("models/train_model")

# Inference
topic_model.transform(docs)
```

**Comment by MaartenGr** [comment]
To use `.transform` with BERTopic, your clustering algorithm also needs to have a `.predict` function. Your clustering algorithm, which is technically your `River()`, needs also have the `.predict` function:

```python
class River:
    def __init__(self, model):
        self.model = model

    def partial_fit(self, umap_embeddings):
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            self.model = self.model.learn_one(umap_embedding)

        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            labels.append(label)

        self.labels_ = labels
        return self

    def predict(self, X):
        do something here
        ....
```

How that specifically looks like depends on your internal clustering algorithm. You can find an example of how that works with `DBSTREAM` [here](https://riverml.xyz/0.15.0/api/cluster/DBSTREAM/#examples).

**Comment by JRatschat** [comment]
Thanks for your advice! I created the following .predict function based on the existing .partial_fit function:

```
def predict(self, umap_embeddings):
        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            labels.append(label)

        self.labels_ = labels
        return self 
```

Now, I get the following error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/qy90eu/.pyenv/versions/3.8.16/envs/setfit3.8/lib/python3.8/site-packages/bertopic/_bertopic.py", line 455, in transform
    predictions = self._map_predictions(predictions)
  File "/Users/qy90eu/.pyenv/versions/3.8.16/envs/setfit3.8/lib/python3.8/site-packages/bertopic/_bertopic.py", line 2838, in _map_predictions
    mapped_predictions = [mappings[prediction]
TypeError: 'River' object is not iterable
```

Do you have any idea on how I could set up the .predict function?

**Comment by JRatschat** [comment]
I used the same code as before with the addition of the .predict function. Here you go:

```
import pandas as pd
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer, OnlineCountVectorizer
from datasets import load_dataset
from river import cluster, stream


# Load dataset
dataset = load_dataset("banking77")
docs = pd.DataFrame(dataset["train"])["text"].head(100).tolist()


class River:
    def __init__(self, model):
        self.model = model

    def partial_fit(self, umap_embeddings):
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            self.model = self.model.learn_one(umap_embedding)

        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            labels.append(label)

        self.labels_ = labels
        return self

    def predict(self, umap_embeddings):
        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            labels.append(label)

        self.labels_ = labels
        return self


# Using DBSTREAM to detect new topics as they come in
cluster_model = River(cluster.DBSTREAM())
vectorizer_model = OnlineCountVectorizer(stop_words="english")
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)

# Prepare model
topic_model = BERTopic(
    hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
)

# Train model
topic_model.partial_fit(docs)

# Save topic model
topic_model.save("models/train_model")

# Load topic model
topic_model = BERTopic.load("models/train_model")

# Inference
topic_model.transform(docs)
```

**Comment by MaartenGr** [comment]
Ah, you will need to return the predictions, not `self`:

https://github.com/MaartenGr/BERTopic/blob/307a15fbec8fc020261ec73cb75daeb1d2e2f5e9/bertopic/_bertopic.py#LL514C17-L514C63

**Comment by JRatschat** [comment]
Thanks so much @MaartenGr! Amazing package btw! 

I got the .transform function running with the following .predict function in the River class:

```
def predict(self, umap_embeddings):
        labels = []
        for umap_embedding, _ in stream.iter_array(umap_embeddings):
            label = self.model.predict_one(umap_embedding)
            labels.append(label)

        self.labels_ = labels
        return labels
```

I am not sure if this `self.labels_ = labels` is really needed, but I kept it for now.

**Comment by MaartenGr** [comment]
Awesome, glad to hear that it worked for you! If you run into any other issues, please let me know!
