### ISSUE TITLE
Can't fit the model

### ISSUE THREAD

**Issue by 761100192** [MaartenGr/BERTopic#1316]
Traceback (most recent call last):
  File "D:\python3.10.11\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 293107

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\bertTopic.py", line 13, in <module>
    topics, probs = topic_model.fit_transform(no_with_photo_texts)
  File "D:\python3.10.11\lib\site-packages\bertopic\_bertopic.py", line 344, in fit_transform
    embeddings = self._extract_embeddings(documents.Document,
  File "D:\python3.10.11\lib\site-packages\bertopic\_bertopic.py", line 2828, in _extract_embeddings
    embeddings = self.embedding_model.embed_documents(documents, verbose)
  File "D:\python3.10.11\lib\site-packages\bertopic\backend\_base.py", line 69, in embed_documents
    return self.embed(document, verbose)
  File "D:\python3.10.11\lib\site-packages\bertopic\backend\_sentencetransformers.py", line 63, in embed
    embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
  File "D:\python3.10.11\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 157, in encode
    sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
  File "D:\python3.10.11\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 157, in <listcomp>
    sentences_sorted = [sentences[idx] for idx in length_sorted_idx]
  File "D:\python3.10.11\lib\site-packages\pandas\core\series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "D:\python3.10.11\lib\site-packages\pandas\core\series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "D:\python3.10.11\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 293107

**Comment by 761100192** [comment]
the model cannot have any special char?

**Comment by MaartenGr** [comment]
Could you share your full code as well as the dependencies in your environment? Based on what I am seeing, there might indeed be something going on with your input data.

**Comment by 761100192** [comment]
solved the issue,thank you so much!

**Comment by MaartenGr** [comment]
Glad to hear that the issue was solved! Feel free to reach out if you run into any other issues.
