### ISSUE TITLE
Error during outlier reduction

### ISSUE THREAD

**Issue by Pratik--Patel** [MaartenGr/BERTopic#1399]
I am doing [outlier reduction using c-tf-idf
](https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html#c-tf-idf)
When I set value of `threshold` to be very small such that we have no outliers at all, I get an error when I trigger `update_topics` to update topics.

Following is the relevant configuration.
```
# embedding model
embedding_model = SentenceTransformer(os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2"))

# vectorizer
vectorizer_model = get_vectorizer_model()

# representation models
llm_name = os.getenv("LLM_FOR_LABEL", "google/flan-t5-base")
generator = pipeline('text2text-generation', model=llm_name)
rp_models = [PartOfSpeech("en_core_web_sm"),MaximalMarginalRelevance(diversity=0.45),TextGeneration(generator, prompt=prompt)]

bert_topic = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    representation_model=rp_models,
    verbose=os.getenv("verbose", False),
    low_memory=True,
    calculate_probabilities=False,
    ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
)
```

Relevant code:

```
logger.info("generating embedding for documents")
embeddings = embedding_model.encode(texts, show_progress_bar=True)

topic_model = bert_topic.fit(texts, embeddings=embeddings)

current_number_of_topics = len(topic_model.get_topics())
logger.info(f"max_topics is {str(max_topics)} current number of topics is {str(current_number_of_topics)}")
if current_number_of_topics > max_topics:
    logger.info(f"reducing topics to {str(max_topics)}")
    topic_model.reduce_topics(texts, nr_topics=max_topics)

# Create and set custom labels if LLM is used for label generation
if using_llm:
    labels = [topic_model.get_topic(topic)[0][0] for topic in sorted(list(set(topic_model.topics_)))]
    topic_model.set_topic_labels(labels)
else:
    labels = []

# get topic to doc mappings
initial_topic_ids, initial_probs = topic_model.transform(texts, embeddings=embeddings)

# Reduce outliers using the `c-tf-idf` strategy
topic_ids = topic_model.reduce_outliers(documents=texts,
                                                topics=initial_topic_ids,
                                                strategy="c-tf-idf",
                                                threshold=threshold_for_outlier_reduction,
                                                embeddings=embeddings)


# Revert update representation back to keywords and use only representation_model_1 and
# representation_model_2 instead
# also update the topics to be new topics generated after reducing outliers
new_rp_models = rp_models[0:2]

topic_model.update_topics(
    texts,
    topics=topic_ids,
    vectorizer_model=vectorizer_model,
    representation_model=new_rp_models,
    ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
)
```

I am not reducing topics/merging topics after calling `update_topics` but I am doing it before which should be ok per documentation but I get following error.

```
[2023-07-03 22:25:15,799: INFO/MainProcess] reducing topics to 50
[2023-07-03 22:25:54,192: INFO/MainProcess] threshold is as follows
[2023-07-03 22:25:54,192: INFO/MainProcess] 0.03
[2023-07-03 22:25:55,444: INFO/MainProcess] calling update_topics with following rp_models
[2023-07-03 22:25:55,444: INFO/MainProcess] PartOfSpeech
[2023-07-03 22:25:55,444: INFO/MainProcess] MaximalMarginalRelevance
[2023-07-03 22:26:16,144: WARNING/MainProcess] --- Logging error ---
[2023-07-03 22:26:16,150: WARNING/MainProcess] Traceback (most recent call last):
[2023-07-03 22:26:16,150: WARNING/MainProcess]   File "/generate_topics.py", line 226, in start_topic_modeling
    topic_model.update_topics(
[2023-07-03 22:26:16,150: WARNING/MainProcess]   File "/opt/conda/lib/python3.10/site-packages/bertopic/_bertopic.py", line 1308, in update_topics
    self.topic_representations_ = self._extract_words_per_topic(words, documents)
[2023-07-03 22:26:16,150: WARNING/MainProcess]   File "/opt/conda/lib/python3.10/site-packages/bertopic/_bertopic.py", line 3201, in _extract_words_per_topic
    topics = tuner.extract_topics(self, documents, c_tf_idf, topics)
[2023-07-03 22:26:16,150: WARNING/MainProcess]   File "/opt/conda/lib/python3.10/site-packages/bertopic/representation/_pos.py", line 145, in extract_topics
    vals = topic_model.c_tf_idf_[:, np.array(word_indices)][topic + topic_model._outliers]
[2023-07-03 22:26:16,150: WARNING/MainProcess]   File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/_index.py", line 47, in __getitem__
    row, col = self._validate_indices(key)
[2023-07-03 22:26:16,150: WARNING/MainProcess]   File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/_index.py", line 155, in _validate_indices
    raise IndexError('row index (%d) out of range' % row)
[2023-07-03 22:26:16,150: WARNING/MainProcess] IndexError: row index (49) out of range
```

Is this a bug or is there any workaround? 

Also, how would you recommend one should determine the optimal value for `threshold` parameter here? Is there any correlation that we can do with respect to number of documents or something like that?

**Comment by MaartenGr** [comment]
I am not entirely sure but I think it might be the case that the model still expects that there are outliers generated in your model. You could do `topic_model._outliers = 0` just before running `.update_topics` and I think the issue should be resolved.
