### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'long'

### ISSUE THREAD

**Issue by kmcclenn** [MaartenGr/BERTopic#1416]
I am trying to import BERTopic, but I am getting this error:

`
Traceback (most recent call last):
  File "/om2/user/kmcclenn/item_analysis/openmind_python_files/scripts/test_script.py", line 92, in <module>
    run()
  File "/om2/user/kmcclenn/item_analysis/openmind_python_files/scripts/test_script.py", line 73, in run
    from bertopic import BERTopic
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/bertopic/__init__.py", line 1, in <module>
    from bertopic._bertopic import BERTopic
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/bertopic/_bertopic.py", line 38, in <module>
    from umap import UMAP
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/umap/__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/umap/umap_.py", line 28, in <module>
    import numba
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/numba/__init__.py", line 16, in <module>
    from numba.core import types, errors
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/numba/core/types/__init__.py", line 108, in <module>
    long_ = _make_signed(np.long)
  File "/net/vast-storage/scratch/vast/gablab/kmcclenn/bin/mambaforge/envs/item-analysis/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'
`

Do you know why?

**Comment by kmcclenn** [comment]
Okay, so I uninstalled numba, reinstalled numba, and then reinstalled bertopic, and now it is giving me this error:
`RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
libsentencepiece.so.0: cannot open shared object file: No such file or directory`

Do you know what this means? I can include the full traceback if you think that would be helpful. Thanks!

**Comment by kmcclenn** [comment]
@MaartenGr I updated my environment (I am not sure specifically what changed) and it worked! Thanks!
