### ISSUE TITLE
Save Colab And Now running From CPU Computer

### ISSUE THREAD

**Issue by firmai** [MaartenGr/BERTopic#165]
Hi, I have saved the model on Colab, and are now reading it in on my PC (cpu only) computer.

Is there a way to get around this message?

```
Traceback (most recent call last):
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/index.py", line 7, in <module>
    from layout import earnings_call_app, news_app, privacy_app, index_app, bankruptcy_app, risk_app, presentation_app, summary_app, script_app, research_app, anomaly_app, weekreport_app
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/layout/earnings_call_app.py", line 13, in <module>
    from constants import *
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/constants.py", line 29, in <module>
    topic_model = BERTopic.load("large_bert_topic_2.m")
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/bertopic/_bertopic.py", line 1236, in load
    topic_model = joblib.load(file)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.9/pickle.py", line 1589, in load_reduce
    stack[-1] = func(*args)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/storage.py", line 161, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

```

**Comment by MaartenGr** [comment]
My advice would be to make sure to always use a GPU when using BERTopic since creating and dealing with the embeddings can be incredibly slow if a GPU is not used. However, I can imagine there are certain cases, for example, visualizations, where a GPU is not needed. In that case, it might be helpful to save the BERTopic model without the embedding model. This allows you to load in the model without needing a GPU. 

It would go something like this:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer

# Prepare your embedding model
embedding_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")

# Train and save the topic model
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic(embedding_model=embedding_model).fit(docs)
topic_model.save("my_model", save_embedding_model=False)
```

Now that you have saved the topic model without the embedding model, you can then load it in and assign it with your embedding model:

```python
my_loaded_topic_model = BERTopic.load("my_model", embedding_model=embedding_model)
```

**Comment by firmai** [comment]
I see, the problem is that I need it to work when for example doing a topic search: for example

![image](https://user-images.githubusercontent.com/26666267/123955193-3fe70980-d9a1-11eb-8b08-16a5487092de.png)

**Comment by firmai** [comment]
The reason this is important is that I want to run it as an app to find the topics, so would it be possible to find the topics using CPU, as I am not entirely sure how to utilise a GPU on an application engine.

**Comment by MaartenGr** [comment]
I just tried it out in a Google colab session and the following seems to work. First, you can train your model using a GPU. Make sure to separate the embedding model from the topic model and save it without the embedding model:

```python
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

sentence_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=sentence_model)
topics, _ = topic_model.fit_transform(docs)
topic_model.save("my_model", save_embedding_model=False)
```

Then, load in the topic model together with your embedding model in your CPU instance like this:

```python
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from bertopic.backend._utils import select_backend

sentence_model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
model = select_backend(sentence_model)
my_loaded_topic_model = BERTopic.load("my_model", embedding_model=model)
```

**Comment by firmai** [comment]
Excellent, I think we are inching closer, we have what I believe to be the last error pop up. When I transfer the model saved on Colab with all the same dependencies as the one I run locally, the local cpu computer gives the following output:

```
topic_model = BERTopic.load("large_bert_topic_4_without.m", embedding_model=model_transform)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/bertopic/_bertopic.py", line 1233, in load
    topic_model = joblib.load(file)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.9/pickle.py", line 1589, in load_reduce
    stack[-1] = func(*args)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/numba/core/serialize.py", 
line 208, in _unpickle__CustomPickled
    ctor, states = loads(serialized)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/numba/core/serialize.py", 
line 112, in _rebuild_function
    code = _rebuild_code(*code_reduced)
  File "/mnt/c/Users/dsnow/GitHub/peopleshf/dashboard/dash-phf/sovai/lib/python3.9/site-packages/numba/core/serialize.py", 
line 132, in _rebuild_code
    raise RuntimeError("incompatible bytecode version")
RuntimeError: incompatible bytecode version
```

I think maybe it might be related to this issue, what would you recommend as a solution?

https://github.com/josephsdavid/N2D/issues/8

**Comment by firmai** [comment]
![image](https://user-images.githubusercontent.com/26666267/124563309-d56a1980-de37-11eb-919e-c502f0dd27b2.png)

this is the colab libraries and they match my local libraries

**Comment by firmai** [comment]
Perhaps the solution is not to use umap, I am not sure? But if so is there an alternative way of saving, or an alternative to using umap?

**Comment by firmai** [comment]
This is local for eg.:

![image](https://user-images.githubusercontent.com/26666267/124564446-fda64800-de38-11eb-9432-7970ce5a37e6.png)

**Comment by MaartenGr** [comment]
Could you perhaps share the entire list of packages installed in both environments? Also, it seems you are using a different python version locally vs. on google colab. Perhaps the issue stems from that mismatch.

**Comment by firmai** [comment]
Yes, the issue stems from that mismatch, thanks.
