### ISSUE TITLE
Error on reducing topics

### ISSUE THREAD

**Issue by typercast** [MaartenGr/BERTopic#172]
Trying to reduce the number of topics, I was faced with the following message:

```
2021-07-06 17:51:31,942 - BERTopic - Reduced number of topics from 88 to 21
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/gpu.py", line 22, in process_bertopic
    topics, probs = topic_model.fit_transform(text)
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/bertopic/_bertopic.py", line 294, in fit_transform
    probabilities = self._map_probabilities(probabilities)
  File "/home/user/miniconda3/envs/fastai/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1671, in _map_probabilities
    new_probabilities[:, to_topic] += new_probabilities[:, from_topic]
IndexError: index 87 is out of bounds for axis 1 with size 87
```

This follows from the following code:

```
topics, probs = topic_model.fit_transform(text)
topic_model.update_topics(text, topics, n_gram_range=(1, 3))
topic_model.reduce_topics(text, topics, nr_topics=20)
topic_model.visualize_topics()
```

Any idea?

**Comment by MaartenGr** [comment]
Which version of BERTopic are you currently using? This seems like it was a bug in a previous version. Also, you could both update and reduce the topics when calling `topic_model = BERTopic(n_gram_range=(1,3), nr_topics=20)`. This might also help preventing the issue.

**Comment by typercast** [comment]
Hi @MaartenGr 

I am using the version 0.8.1. Your solution does seem to work so far :), but only if the number of topics found is larger than nr_topics. That is, if it found only 5 topics and I added nr_topics = 20, then an error occurs. Is it possible to fix 20 as the max number of topics, but allow it to be smaller if the number of clusters is fewer than that?

**Comment by MaartenGr** [comment]
Great to hear that it is working currently. I would, for now, advise you to use `nr_topics = "auto"` instead. It allows you to reduce the number of topics automatically before it forces to merge topics that should not be merged. Also, I would advise you to reduce `min_topic_size` as you are getting too few topics. Typically, I would expect a model to get at least 50 topics.

**Comment by typercast** [comment]
Thanks for the tips! Have a great day.
