### ISSUE TITLE
SpaCy installed but PartOfSpeech not working

### ISSUE THREAD

**Issue by wuziyigit** [MaartenGr/BERTopic#1741]
I get the following error when running the code:

import spacy
import bertopic
from bertopic.representation import PartOfSpeech
aspect_model1 = PartOfSpeech("en_core_web_sm")

Error message:

Traceback (most recent call last):
  File "C:\Users\w\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-65-e76517097305>", line 1, in <module>
    aspect_model1 = PartOfSpeech("en_core_web_sm")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wzy98\Documents\Temp files\New Files\Academic Papers\SU19 China Shock\Twitter_0111\scrapfly\venv\Lib\site-packages\bertopic\_utils.py", line 100, in __call__
    raise ModuleNotFoundError(self.msg)
ModuleNotFoundError: In order to use Part of Speech with Spacy you will need to install via;
pip install bertopic[spacy]

I tried pip install bertopic[spacy] in terminal, but it does not work. Using python 3.11, spaCy 3.7.2

**Comment by MaartenGr** [comment]
If BERTopic cannot find SpaCy, then it is possible it was not installed in your current environment. Make sure that you select the correct kernel/environment when installing and using BERTopic.

**Comment by rmlopes** [comment]
Hi, I am stumbling on the same issue.

Python 3.12.7
Spacy 3.8.4

Trying to install the optional `bertopic[spacy]` pip complains that it cannot be found:

`no matches found: bertopic[spacy]`
