### ISSUE TITLE
Supervised Topic Modelling: fit() got an unexpected keyword argument 'y'

### ISSUE THREAD

**Issue by souravmpi** [MaartenGr/BERTopic#198]
Hi, Thanks a lot for sharing the library. I was looking into using it for supervised topic modelling, however ran into the following error. Can you please suggest what I am doing wrong here. Thanks,

```
train_data: list of strings
train_labl: list of strings
```

`topic_model = BERTopic(verbose=True).fit(train_data, y=train_labl)`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: fit() got an unexpected keyword argument 'y'
```

**Comment by MaartenGr** [comment]
Most likely, this means you are using an older version of BERTopic. If you upgrade to the latest version, I believe this will be fixed: 

`pip install --upgrade bertopic`

**Comment by souravmpi** [comment]
Hi.. Thanks for the reply. I updated to the latest version - during which torch was updated to v1.9.0. Then, it throws the following error. I have installed bertopic[all].

```
>>> from bertopic import BERTopic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/bertopic/__init__.py", line 1, in <module>
    from bertopic._bertopic import BERTopic
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/bertopic/_bertopic.py", line 16, in <module>
    from sentence_transformers import SentenceTransformer
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/sentence_transformers/SentenceTransformer.py", line 11, in <module>
    import transformers
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/transformers/__init__.py", line 626, in <module>
    from .trainer import Trainer
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/transformers/trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File "/tf/sourav/bertopic/lib/python3.6/site-packages/transformers/trainer_pt_utils.py", line 40, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING'
```

**Comment by MaartenGr** [comment]
Hmmmm, this seems to be an issue with pytorch not being compatible with some of the packages. I would advise not using `pip install bertopic[all]` but only the one that you are going to be using. It will be discontinued in a later update as some packages do not work well together.

**Comment by MaartenGr** [comment]
You can also check out the thread [here](https://github.com/MaartenGr/BERTopic/issues/71) for some more help on this issue.

**Comment by souravmpi** [comment]
Hi.. Thanks... yes, using the simple installation fixes the import error.
However, the unexpected keyword error persists.
