### ISSUE TITLE
Installing bertopic cause Spyder 5.5.1 in Anaconda to not launch ith errors.

### ISSUE THREAD

**Issue by rdsch2** [MaartenGr/BERTopic#2070]
After upgrading Anaconda to 2.6.1 Spyder 5.5.1 which is installed does not launch after installing latest Bertopic (from conda-forge).  These are the errors.   Sypder launched before installing bertopic.

 Traceback (most recent call last):
File "/opt/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/opt/anaconda3/lib/python3.12/site-packages/spyder/app/start.py", line 25, in 
import ctypes
File "/opt/anaconda3/lib/python3.12/ctypes/__init__.py", line 8, in 
from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/anaconda3/lib/python3.12/lib-dynload/_ctypes.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace (_CFBundleGetVersionNumber)

**Comment by MaartenGr** [comment]
This does not seem to be related to BERTopic but instead your spyder environment. Instead, I would advise starting from a completely clean and fresh environment before continuing.

**Comment by ashwinc04** [comment]
same issue. all i did was to install spyder-notebook with the command "conda install spyder-notebook -c conda-forge" which is from spyder's official document [+] but it just broke spyder
[+] https://docs.spyder-ide.org/current/plugins/notebook.html
