### ISSUE TITLE
numpy.core._exceptions.MemoryError:

### ISSUE THREAD

**Issue by ginward** [MaartenGr/BERTopic#276]
@MaartenGr This is related to the following issue: https://github.com/MaartenGr/BERTopic/issues/151 and perhaps this one too: https://github.com/MaartenGr/BERTopic/issues/267

I have solved the bottle neck in processing large data with UMAP and HDBSCAN. However, there seems to be another bottleneck in the final stage where words are extracted from topics:
```
vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words="english")

umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', low_memory = False, verbose=True, init=embeddings_init)

# Setting HDBSCAN model
hdbscan_model = HDBSCAN(min_cluster_size=100, min_samples=1, metric='euclidean', cluster_selection_method='eom', prediction_data=True, core_dist_n_jobs=5)

topic_model = BERTopic(umap_model = umap_model, hdbscan_model=hdbscan_model,  verbose=True, seed_topic_list=seed_topic_list, low_memory=False, calculate_probabilities=False, vectorizer_model=vectorizer_model)



#topics, probs = topic_model.fit_transform(docs)

topic_model = topic_model.fit(docs, embeddings)
```

```
Construct fuzzy simplicial set
Sat Oct  9 12:55:20 2021 Finding Nearest Neighbors
Sat Oct  9 12:55:25 2021 Building RP forest with 64 trees
Sat Oct  9 13:04:12 2021 NN descent for 23 iterations
���������1  /  23
���������2  /  23
���������3  /  23
���������4  /  23
���������5  /  23
���������6  /  23
���������7  /  23
���������8  /  23
���������9  /  23
���������10  /  23
��������Stopping threshold met -- exiting after 10 iterations
Sat Oct  9 13:38:29 2021 Finished Nearest Neighbor Search
Sat Oct  9 13:40:22 2021 Construct embedding
��������completed  0  /  200 epochs
��������completed  20  /  200 epochs
��������completed  40  /  200 epochs
��������completed  60  /  200 epochs
��������completed  80  /  200 epochs
��������completed  100  /  200 epochs
��������completed  120  /  200 epochs
��������completed  140  /  200 epochs
��������completed  160  /  200 epochs
��������completed  180  /  200 epochs
Sat Oct  9 14:55:35 2021 Finished embedding
2021-10-09 18:53:38,790 - BERTopic - Clustered UMAP embeddings with HDBSCAN
Traceback (most recent call last):
  File "BERTopic.py", line 62, in <module>
    topic_model = topic_model.fit(docs, embeddings)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 212, in fit
    self.fit_transform(documents, embeddings, y)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 298, in fit_transform
    self._extract_topics(documents)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1447, in _extract_topics
    self.topics = self._extract_words_per_topic(words)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/bertopic/_bertopic.py", line 1618, in _extract_words_per_topic
    c_tf_idf = self.c_tf_idf.toarray()
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 1031, in toarray
    out = self._process_toarray_args(order, out)
  File "/scratch/ap248/nlp_env38/lib/python3.8/site-packages/scipy/sparse/base.py", line 1202, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 2.82 TiB for an array with shape (8701, 44552600) and data type float64
```

As mentioned in the previous issue, I have (10 million, 384) embedding shape reduced to 5 dimensions with UMAP successfully. I have a machine with 1.5TB memory. Any idea how to solve the above issue? 

Looks like the problem happened here: https://github.com/MaartenGr/BERTopic/blob/0b321678ffe4eab0a28484faf76728f584a94ebd/bertopic/_bertopic.py#L1618 

Is it possible not to convert the TFIDF matrix to an array? Why is there a matrix of the shape `(8701, 44552600)`? Does it mean that I have 8701 clusters and 4.4 million words and bigrams?

**Comment by ginward** [comment]
The pull request does seem to work. Thanks!
