### ISSUE TITLE
Why the mode is still needed to be fit after loading the model?

### ISSUE THREAD

**Issue by paraself** [MaartenGr/BERTopic#298]
Hello, thanks for making this great package.

I trained the model and saved it.
```
topic_model = BERTopic(embedding_model=sentence_model, verbose=True, n_gram_range=(1,3), calculate_probabilities=False)
topic_model.fit(docs)
topic_model.save('pracs', save_embedding_model=False)
```

then in another process load the model, then get topics
```
topic_model = BERTopic(embedding_model=sentence_model, verbose=True, n_gram_range=(1,3), calculate_probabilities=False)
topic_model.load('pracs')
print(topic_model.get_topic_info())
```

However, it throw errors:
```
Traceback (most recent call last):
  File "src/topic.py", line 21, in <module>
    print(topic_model.get_topic_info())
  File "./deps/bertopic/_bertopic.py", line 741, in get_topic_info
    check_is_fitted(self)
  File "./deps/bertopic/_utils.py", line 67, in check_is_fitted
    raise ValueError(msg % {'name': type(model).__name__})
ValueError: This BERTopic instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
```

Why the model still need to be fit after loading it successfully?
I'd like to train the model offline ,then predict new document in a web service.

**Comment by MaartenGr** [comment]
The function is a class method that is primarily used to make sure that the model is loaded in isolation, so without the need to first instantiate a model. By making it a class method, we can directly load the model in from the class.

**Comment by paraself** [comment]
Clear! Thanks
