### ISSUE TITLE
Linux kills process during fit_transform (memory error?)

### ISSUE THREAD

**Issue by Rysias** [MaartenGr/BERTopic#324]
First and foremost, thanks for a magnificent package!

I'm fitting ~1.6 million tweets and embeddings (which I have pre-calculated; size ~9.6GB) using following the [FAQ on memory issues](https://maartengr.github.io/BERTopic/faq.html#i-am-facing-memory-issues-help). The problematic code looks as follows: 
```
vectorizer_model = CountVectorizer(ngram_range=(1, 2), stop_words="english", min_df=100)

topic_model = BERTopic(
        low_memory=True,
        vectorizer_model=vectorizer_model,
        verbose=True,
        calculate_probabilities=False,
    )

topics, probs = topic_model.fit_transform(docs, embeddings)
```
When runnning this through a bash-scrip I get the following dangerous looking error: "Memory cgroup out of memory: Killed process 28848 (python) total-vm:62997452kB, anon-rss:45998236kB, file-rss:3832kB, shmem-rss:4kB, UID:11042 pgtables:108112kB oom_score_adj:-998"

Any pieces of advice as to what I should do?

**Comment by MaartenGr** [comment]
Thank you for the extensive description and glad to see that you followed the FAQ! Shame that you still get memory issues though. In general, ~1.6 millions tweets is quite a lot especially considering the memory needed to keep the embeddings in memory during UMAP and HDBSCAN clustering. Having said that, do you have any idea where the memory issue starts happening? In other words, since you have verbose=True, which steps have already passed (UMAP, HDBSCAN, c-TF-IDF, etc.)? Also, how much RAM do you have available on your machine or environment?

Regardless of the answers above, a solution is fitting on a smaller portion of the data (e.g., 300.000 tweets) and transforming all other tweets. Typically, those 300.000 tweets should be more than sufficient in creating a good representation. Lastly, it might even help increasing `min_topic_size` as you will most likely get tens of thousands of topics with a topic size of 15. Setting that to 1000 might help HDBSCAN converge faster.

**Comment by Rysias** [comment]
Thanks for the quick reply! Regarding the output of verbose, it doesn't print anything so I assume the memory issue starts with the first step? 
Also thanks for the suggestion to sample the tweets - I'll definitely try  that. I will also try tuning the topic size a bit :))

**Comment by MaartenGr** [comment]
Hmmm, it would actually be surprised that the issue would stem from UMAP. Typically, it is either c-TF-IDF or HDBSCAN that might run into issues. If it does not work out, let me know!

**Comment by Rysias** [comment]
Ok, I tried to run it and there was some progress! However, I now run into this nasty looking error after the UMAP-step (see below). Any words of wisdom here? :))  
2021-11-12 08:27:52,813 - BERTopic - Reduced dimensionality with UMAP
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "sklearn/neighbors/_binary_tree.pxi", line 1057, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__
  File "sklearn/neighbors/_binary_tree.pxi", line 999, in sklearn.neighbors._kd_tree.BinaryTree._update_memviews
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/XAI21/ExplainlpTwitter/create_topic.py", line 75, in <module>
    main(args)
  File "/work/XAI21/ExplainlpTwitter/create_topic.py", line 46, in main
    topics, probs = topic_model.fit_transform(small_docs, small_embs)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/bertopic/_bertopic.py", line 297, in fit_transform
    documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/bertopic/_bertopic.py", line 1389, in _cluster_embeddings
    self.hdbscan_model.fit(umap_embeddings)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/hdbscan/hdbscan_.py", line 919, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/hdbscan/hdbscan_.py", line 610, in hdbscan
    (single_linkage_tree, result_min_span_tree) = memory.cache(
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/hdbscan/hdbscan_.py", line 275, in _hdbscan_boruvka_kdtree
    alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
  File "hdbscan/_hdbscan_boruvka.pyx", line 392, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__
  File "hdbscan/_hdbscan_boruvka.pyx", line 426, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/home/ucloud/.conda/envs/bertopic/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

**Comment by Rysias** [comment]
It's probably related to #151, and it seems the best solution is to reduce the dataset to ~100k (or meddle with the umap)

**Comment by MaartenGr** [comment]
Ah, in that case, that error might be prevented by simply pip installing the master branch of the HDBSCAN repo. The issue with large data was fixed but not yet pushed to the pypi instance.

**Comment by MaartenGr** [comment]
Due to inactivity, I am going to close this issue. If you are still experiencing this issue, let me know! I'll reopen it and we can discuss it further.
