### ISSUE TITLE
AttributeError when loading topic model

### ISSUE THREAD

**Issue by Rysias** [MaartenGr/BERTopic#326]
Heyhey! I try to load a model using `topic_model = BERTopic.load(TOPIC_PATH)`. This gives me the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jhr\Anaconda3\envs\bertopic_explore\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\jhr\Anaconda3\envs\bertopic_explore\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\jhr\Anaconda3\envs\bertopic_explore\lib\pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "C:\Users\jhr\Anaconda3\envs\bertopic_explore\lib\pickle.py", line 1537, in load_stack_global
    self.append(self.find_class(module, name))
  File "C:\Users\jhr\Anaconda3\envs\bertopic_explore\lib\pickle.py", line 1581, in find_class
    return _getattribute(sys.modules[module], name)[0]
  File "C:\Users\jhr\Anaconda3\envs\bertopic_explore\lib\pickle.py", line 331, in _getattribute
    raise AttributeError("Can't get attribute {!r} on {!r}"
AttributeError: Can't get attribute 'TopicMapper' on <module 'bertopic._bertopic' from 'C:\\Users\\jhr\\Anaconda3\\envs\\bertopic_explore\\lib\\site-packages\\bertopic\\_bertopic.py'>

The model was saved on a linux machine, and attempted loaded on a linux machine both with bertopic v.0.9.3 (I think). What might be the issue?

**Comment by MaartenGr** [comment]
I am not familiar with this issue. I just tested it out on a Google Colab session and I have no issues with v0.9.3. I would advise making sure that the environments are the same and that BERTopic has the version across environments.

**Comment by Rysias** [comment]
This was indeed because of a version mismatch between v0.9.1 and v0.9.3 - thanks for the assistance!
