### ISSUE TITLE
"Ignored Uknown kwarg..." error persisting

### ISSUE THREAD

**Issue by nzaw96** [MaartenGr/BERTopic#487]
Hi Maarten,
      I just installed BERTopic and was trying to use it do Topic Modeling on addiction dataset I scraped off of Reddit. I kept getting the following error:

runfile('/Users/nayza/Desktop/YTproject/AAHSA/addictionStudy_2.py', wdir='/Users/nayza/Desktop/YTproject/AAHSA')
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
Traceback (most recent call last):

File "/Users/nayza/Desktop/YTproject/AAHSA/addictionStudy_2.py", line 30, in <module>
    topic_model_1.fit_transform(beforedf_C['body'].tolist())

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/bertopic/_bertopic.py", line 286, in fit_transform
    embeddings = self._extract_embeddings(documents.Document,

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/bertopic/_bertopic.py", line 1343, in _extract_embeddings
    embeddings = self.embedding_model.embed_documents(documents, verbose)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/bertopic/backend/_base.py", line 69, in embed_documents
    return self.embed(document, verbose)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/bertopic/backend/_sentencetransformers.py", line 63, in embed
    embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 164, in encode
    out_features = self.forward(features)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 66, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 996, in forward
    encoder_outputs = self.encoder(

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 585, in forward
    layer_outputs = layer_module(

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 472, in forward
    self_attention_outputs = self.attention(

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 402, in forward
    self_outputs = self.self(

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/transformers/models/bert/modeling_bert.py", line 268, in forward
    mixed_query_layer = self.query(hidden_states)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)

  File "/Users/nayza/opt/anaconda3/envs/nz_venv1/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)

KeyboardInterrupt

This went on. I've been trying to find the solution for the past hour without any success. Any suggestions. If this is the issue with the version of tokenizer or BERTopic how do I update them?

**Comment by MaartenGr** [comment]
I believe this is an issue with either the transformers version or the tokenizer version. To view which version you have, you can run `pip freeze` to get a full list of all packages. Based on that, I would advise following some of the steps [here](https://github.com/huggingface/transformers/issues/15358). There, you can find several steps for solving the output that you are having.

**Comment by MaartenGr** [comment]
Since this issue has not been active for a while, I am going to close this for now. Having said that, if you are still experiencing this issue, let me know and we'll see what we can do about that.
