### ISSUE TITLE
UMAP: BrokenProcessPool

### ISSUE THREAD

**Issue by aph61** [MaartenGr/BERTopic#521]
when running the fit_transform module the program throws the error:

```
2022-04-27 16:50:07,357 - BERTopic - Reduced dimensionality with UMAP
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "sklearn/neighbors/_binary_tree.pxi", line 1057, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__
  File "sklearn/neighbors/_binary_tree.pxi", line 999, in sklearn.neighbors._kd_tree.BinaryTree._update_memviews
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
"""
```

and 
```
"""
BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all pickable.
"""

```
This happens on an AWS cloud server where default mode is multi-processor; when I run the same code with the same data on my machine I do not have that problem. So it appears to  a multi-processor problem. Is this a trivial incompatible version-issue (that can be solved quickly) or (very drastic), is there a way to prevent the code running in multi-processor mode? Something like a directive: no-multiprocessor (I'm always into the QuaD solutions)

Thanks,

Andreas

The full dump

```
2022-04-27 15:33:52,265 - BERTopic - Reduced dimensionality with UMAP
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "sklearn/neighbors/_binary_tree.pxi", line 1057, in sklearn.neighbors._kd_tree.BinaryTree.__setstate__
  File "sklearn/neighbors/_binary_tree.pxi", line 999, in sklearn.neighbors._kd_tree.BinaryTree._update_memviews
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.8/site-packages/bertopic/_bertopic.py in fit_transform(self, documents, embeddings, y)
    289 
    290         # Cluster UMAP embeddings with HDBSCAN
--> 291         documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)
    292 
    293         # Sort and Map Topic IDs by their frequency

~/.local/lib/python3.8/site-packages/bertopic/_bertopic.py in _cluster_embeddings(self, umap_embeddings, documents)
   1377             probabilities: The distribution of probabilities
   1378         """
-> 1379         self.hdbscan_model.fit(umap_embeddings)
   1380         documents['Topic'] = self.hdbscan_model.labels_
   1381         probabilities = self.hdbscan_model.probabilities_

~/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py in fit(self, X, y)
    917          self._condensed_tree,
    918          self._single_linkage_tree,
--> 919          self._min_spanning_tree) = hdbscan(X, **kwargs)
    920 
    921         if self.prediction_data:

~/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py in hdbscan(X, min_cluster_size, min_samples, alpha, cluster_selection_epsilon, metric, p, leaf_size, algorithm, memory, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, cluster_selection_method, allow_single_cluster, match_reference_implementation, **kwargs)
    608                                            gen_min_span_tree, **kwargs)
    609             else:
--> 610                 (single_linkage_tree, result_min_span_tree) = memory.cache(
    611                     _hdbscan_boruvka_kdtree)(X, min_samples, alpha,
    612                                              metric, p, leaf_size,

~/.local/lib/python3.8/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

~/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py in _hdbscan_boruvka_kdtree(X, min_samples, alpha, metric, p, leaf_size, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, **kwargs)
    273 
    274     tree = KDTree(X, metric=metric, leaf_size=leaf_size, **kwargs)
--> 275     alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
    276                                  leaf_size=leaf_size // 3,
    277                                  approx_min_span_tree=approx_min_span_tree,

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__()

hdbscan/_hdbscan_boruvka.pyx in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds()

~/.local/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1054 
   1055             with self._backend.retrieval_context():
-> 1056                 self.retrieve()
   1057             # Make sure that we get a last message telling us we are done
   1058             elapsed_time = time.time() - self._start_time

~/.local/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    933             try:
    934                 if getattr(self._backend, 'supports_timeout', False):
--> 935                     self._output.extend(job.get(timeout=self.timeout))
    936                 else:
    937                     self._output.extend(job.get())

~/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

/usr/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

/usr/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by MaartenGr** [comment]
Seeing the issue, I believe this is not related to UMAP but rather to HDBSCAN. Can you try upgrading HDBSCAN to version v0.8.28 in both environments? This error has been mentioned before [here](https://github.com/MaartenGr/BERTopic/issues/338) and [here](https://github.com/MaartenGr/BERTopic/issues/375) and was resolved by upgrading HDBSCAN to the most recent state of the master branch.

**Comment by aph61** [comment]
Hi,

thanks, I re-installed the two libraries from the respective githubs, and it works like a charm.

A side issue, the model is obviously a binary. That makes it very difficult (impossible for me at least) to transfer between different platforms (ubuntu @ my laptop and at the AWS). Do you know of a trick that improves platform-compatibility?

**Comment by MaartenGr** [comment]
> I re-installed the two libraries from the respective githubs, and it works like a charm.

Glad to hear that it works now!

> A side issue, the model is obviously a binary. That makes it very difficult (impossible for me at least) to transfer between different platforms (ubuntu @ my laptop and at the AWS). Do you know of a trick that improves platform-compatibility?

Unfortunately, I have not encountered that specific situation before so I am not entirely sure of the best approach to handle that. It is definitely not ideal but experimentation can be done on the laptop and the final training pipeline at AWS. If you figure out a good way in approaching it, please let me know!

**Comment by aph61** [comment]
will do
