### ISSUE TITLE
Conflicting dependencies with BERTopic and PyTorch Preview

### ISSUE THREAD

**Issue by leifericf** [MaartenGr/BERTopic#560]
Software:

```
System Version: macOS 12.4 (21F79)
Kernel Version: Darwin 21.5.0
Boot Volume: Macintosh HD
Boot Mode: Normal
Computer Name: MacBook Pro
User Name: [Redacted]
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled
Time since boot: 5 days 8:53
```

Hardware:

```
Model Name: MacBook Pro
Model Identifier: MacBookPro18,1
Chip: Apple M1 Pro
Total Number of Cores: 10 (8 performance and 2 efficiency)
Memory: 16 GB
System Firmware Version: 7459.121.3
OS Loader Version: 7459.121.3
Serial Number (system): [Redacted]
Hardware UUID: [Redacted]
Provisioning UDID: [Redacted]
Activation Lock Status: Enabled
```

Steps to reproduce the error:

```
$ conda config --set unsatisfiable_hints True

$ conda create --name pytorch-nightly python=3.10.4 --no-default-packages

$ conda activate pytorch-nightly

$ conda install pytorch -c pytorch-nightly

$ conda install -c conda-forge bertopic=0.10.0 -v
```

Notice error:

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/cli/install.py", line 259, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 313, in solve_final_state
    ssc = self._add_specs(ssc)
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 744, in _add_specs
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1114, in __call__
    return func(*args, **kwargs)
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 86, in main_subshell
    exit_code = do_call(args, p)
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
    return getattr(module, func_name)(args, parser)
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/cli/install.py", line 318, in install
    raise e
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/cli/install.py", line 305, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 313, in solve_final_state
    ssc = self._add_specs(ssc)
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 742, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "~/opt/miniconda3/lib/python3.10/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by leifericf** [comment]
I got it working by repeating the steps above with `python=3.9.13`.

However, I had to install PyTorch Preview (Nightly) build one more time after installing BERTopic, because installing BERTopic replaced `pytorch=1.13.0.dev20220611=py3.9_0` with `pytorch=1.11.0`.

So the dependency conflicts seem to have something to do with the version of Python used.

**Comment by MaartenGr** [comment]
Interesting, if I am not mistaken, [this](https://github.com/pytorch/pytorch/issues/66424) suggests that most recent Pytorch nightly does support python 3.10 which means that there is some other package that has trouble with that python version. 

Checking back some issues ([this issue](https://github.com/MaartenGr/BERTopic/issues/519)), the culprit might be `sentencepiece` but checking their issues page suggests that this is currently resolved ([this issue](https://github.com/google/sentencepiece/issues/732)). So I am not entirely sure where this issue exactly stems from.

**Comment by leifericf** [comment]
Yeah, it could be! In any case, it works very well now. And it's pretty fast, too!

**Comment by leifericf** [comment]
I suppose this issue can be closed, as it is solved by using an older version of Python.
