### ISSUE TITLE
ValueError: k must be less than or equal to the number of training points

### ISSUE THREAD

**Issue by EvyW** [MaartenGr/BERTopic#59]
Hi Maarten,

I'm trying to get a topic on just a list of words: coffee, alcohol, drunk, cigarettes, smoking, drugs. So that I can have a topic called "Addiction" for example.

This is my code

```
from bertopic import BERTopic

docs = ['[CLS]', '[UNK]', 'coffee', 'alcohol', '[UNK]', 'drunk', 'cigarettes', 'smoking', 'drugs', '[SEP]']

model = BERTopic(verbose=True)
topics = model.fit_transform(docs)
```

And this is the error that I'm getting:

```
2021-02-08 23:08:18,794 - BERTopic - Loaded embedding model
2021-02-08 23:08:18,856 - BERTopic - Transformed documents to Embeddings
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/umap/umap_.py:2214: UserWarning: n_neighbors is larger than the dataset size; truncating to X.shape[0] - 1
  warn(
2021-02-08 23:08:21,252 - BERTopic - Reduced dimensionality with UMAP
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bertopic/_bertopic.py", line 278, in fit_transform
    documents, probabilities = self._cluster_embeddings(umap_embeddings, documents)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bertopic/_bertopic.py", line 753, in _cluster_embeddings
    self.cluster_model = hdbscan.HDBSCAN(min_cluster_size=self.min_topic_size,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 922, in fit
    self.generate_prediction_data()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 961, in generate_prediction_data
    self._prediction_data = PredictionData(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/hdbscan/prediction.py", line 104, in __init__
    self.core_distances = self.tree.query(data, k=min_samples)[0][:, -1]
  File "sklearn/neighbors/_binary_tree.pxi", line 1342, in sklearn.neighbors._kd_tree.BinaryTree.query
ValueError: k must be less than or equal to the number of training points
```

Can it be something in the parameter settings? I can't figure it out, any help is very appreciated.

**Comment by MaartenGr** [comment]
There are several things happening here. 

First, it seems that you are passing a list of words that are already in a topic. Typically, you would pass a list of documents where not all documents have exactly the same topic. The goal of BERTopic is not to create a name for a pre-computed topic but to find topics from documents with many different topics. 

Second, BERTopic works best if you pass in a list of documents and not a list of words. Although a list of words will work with UMAP and HDBSCAN, extracting the topic representation will then fail since only unique words are used and there are no words that are shared between documents. 

Third, you are passing very little data to BERTopic and UMAP has a minimum topic size of 10. This means that a topic should have at least 10 documents before being considered a topic. In practice, it is best to use at least 1000 documents and set the `min_topic_size` to 5 in order to create more topics. 

Remember that BERTopic is a clustering technique, which means that it does not work if there is nothing to be clustered. In your case, not only do you have little data but the data only contains a single topic! 

In sum, pass in documents instead of words and make sure that you have at least 1000 documents while setting `min_topic_size` to a low value to allow for multiple topics/clusters to be created.
