### ISSUE TITLE
Import Error on torch : import SAVE_STATE_WARNING

### ISSUE THREAD

**Issue by Lamiv** [MaartenGr/BERTopic#71]
I get an import error with version 0.6.0, on python 3.7.1 env. running on windows.
Traceback as give below:
`>>> from bertopic import BERTopic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File " ..\anaconda3\envs\transformers\lib\site-packages\bertopic\__init__.py", line 1, in <module>
    from bertopic._bertopic import BERTopic
  File " ..\anaconda3\envs\transformers\lib\site-packages\bertopic\_bertopic.py", line 16, in <module>
    from sentence_transformers import SentenceTransformer
  File " ..\anaconda3\envs\transformers\lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File " ..\anaconda3\envs\transformers\lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File " ..\anaconda3\envs\transformers\lib\site-packages\sentence_transformers\datasets\ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File " ..\anaconda3\envs\transformers\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 11, in <module>
    import transformers
  File " ..\anaconda3\envs\transformers\lib\site-packages\transformers\__init__.py", line 626, in <module>
    from .trainer import Trainer
  File " ..\anaconda3\envs\transformers\lib\site-packages\transformers\trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File " ..\anaconda3\envs\transformers\lib\site-packages\transformers\trainer_pt_utils.py", line 40, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' ( ..\anaconda3\envs\transformers\lib\site-packages\torch\optim\lr_scheduler.py)`

**Comment by Lamiv** [comment]
Likely caused by import transformers. issue resolved by upgrading transformers package.

**Comment by freeIsa** [comment]
Having the same error, I tried upgrading transformers but then I got
`flair 0.7 requires transformers<=3.5.1,>=3.5.0, but you have transformers 4.9.1 which is incompatible.`

Any hint on how to fix that? Thank you in advance,

Isabella

**Comment by MaartenGr** [comment]
@freeIsa How did you install BERTopic? It might help installing from a fresh environment. Otherwise, it seems that you can simply install the right transformers version for it to be fixed.

**Comment by freeIsa** [comment]
I tried to uninstall & then install again and the error disappeared. I had some more trouble trying to upgrade to the current version of BERTopic from v. 0.6 (the one I got through `pip install`) because of dependencies (numpy 1.20, which in turn required python >= 3.7), but finally with a new conda environment I was able to get everything up & working! 
Thank you @MaartenGr for your work!
