### ISSUE TITLE
reduce_topics() returning TypeError

### ISSUE THREAD

**Issue by irfan-mekic** [MaartenGr/BERTopic#766]
I have a fit topic model, and when I try to reduce the number of topics to 30, I get the following error:

TypeError: cannot unpack non-iterable BERTopic object

The code Im using is the following:

`reduced_topics, reduced_probs = topic_model.reduce_topics(
                df['segments_conj'], 30
            )`

**Comment by MaartenGr** [comment]
If you are using BERTopic v0.12, then the way you do the topic reductions was updated. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html).

**Comment by vaishnavivisweswaraiah** [comment]
Facing the same issue on BERTopic 0.14 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/28334626/236851157-169f53a7-7a49-499b-bb3b-08a38255ecda.png">

**Comment by MaartenGr** [comment]
@vaishnavivisweswaraiah The v0.14 version does not return any variables I believe. It is best to follow the [documentation](https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html#topic-reduction-after-training) on this!

**Comment by wuziyigit** [comment]
Had a similar issue:

topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True)
topics, probs = topic_model.fit(reps_docs)
2024-01-12 16:02:45,074 - BERTopic - Embedding - Transforming documents to embeddings.
12-Jan-24 16:02:45 - Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
12-Jan-24 16:02:45 - Use pytorch device: cpu
Batches: 100%|██████████| 39/39 [00:16<00:00,  2.42it/s]
2024-01-12 16:03:01,285 - BERTopic - Embedding - Completed ✓
2024-01-12 16:03:01,285 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-01-12 16:03:05,416 - BERTopic - Dimensionality - Completed ✓
2024-01-12 16:03:05,416 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-01-12 16:03:05,587 - BERTopic - Cluster - Completed ✓
2024-01-12 16:03:05,589 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-01-12 16:03:05,693 - BERTopic - Representation - Completed ✓
Traceback (most recent call last):
  File "C:\Users\w\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-79-65ce3cd35c9e>", line 2, in <module>
    topics, probs = topic_model.fit(reps_docs)
    ^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable BERTopic object

**Comment by MaartenGr** [comment]
@wuziyigit Make sure you follow the documentation. `.fit` returns a BERTopic model, not `topics, probs`. You need to use `.fit_transform` for that.

**Comment by MaartenGr** [comment]
@Doracoco `.reduce_topics` does not return anything, so there is your issue. Please check the documentation on how to use the method.
