### ISSUE TITLE
Loading saved model error problem

### ISSUE THREAD

**Issue by satrio-yudhoatmojo** [MaartenGr/BERTopic#804]
I ran fit and transform on a different machine that has high specification and save the model and I also reduced the topics and save the result.

But, when I try to load the saved models in my computer, I got this error:

>>> from bertopic import BERTopic
>>> topic_model = BERTopic.load("mymodel.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\bertopic\_bertopic.py", line 2197, in load
    topic_model = joblib.load(file)
  File "C:\Users\\****\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\numpy_pickle.py", line 577, in load
    obj = _unpickle(fobj)
  File "C:\Users\\****\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\\****\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Users\\****\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1590, in load_reduce
    stack[-1] = func(*args)
  File "C:\Users\\****\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\serialize.py", line 97, in _unpickle__CustomPickled
    ctor, states = loads(serialized)
TypeError: 'bytes' object cannot be interpreted as an integer
>>>

**Comment by MaartenGr** [comment]
I believe I have not seen this error before. However, did you make sure that the environment in which you saved the model has the same structure as the one in which you loaded the model? It is important the dependencies are kept the same throughout environments and changes might break the model.

**Comment by shashankgaur3** [comment]
You need to load the file as stream, the Folder object is the location where the file resides. 
Below code solves the issue for me:

```
import shutil
with Topic_Model_folder.get_download_stream("<filename>") as stream, open("<filename>,'wb') as f_local:
    shutil.copyfileobj(stream,f_local)

cu_topic_model= BERTopic.load("cu_Topic_Model")
```
