### ISSUE TITLE
installation error on Python 3.8.6:  AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by YukunYangNPF** [MaartenGr/BERTopic#89]
```Collecting bertopic[visualization]
  Using cached bertopic-0.6.0-py2.py3-none-any.whl (25 kB)
Collecting pandas>=1.1.5
  Using cached pandas-1.2.3-cp38-cp38-macosx_10_9_x86_64.whl (10.5 MB)
Collecting sentence-transformers>=0.4.1
  Using cached sentence-transformers-1.0.4.tar.gz (74 kB)
Requirement already satisfied: tqdm>=4.41.1 in ./Library/Python/3.8/lib/python/site-packages (from bertopic[visualization]) (4.49.0)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in ./Library/Python/3.8/lib/python/site-packages (from bertopic[visualization]) (0.23.2)
Collecting umap-learn>=0.5.0
  Using cached umap-learn-0.5.1.tar.gz (80 kB)
Collecting hdbscan>=0.8.27
  Using cached hdbscan-0.8.27.tar.gz (6.4 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/3p/tl7jb2gx6b93dg4cq8mxhf7w0000gn/T/pip-build-env-p2nuh67k/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/3p/tl7jb2gx6b93dg4cq8mxhf7w0000gn/T/pip-build-env-p2nuh67k/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.```

**Comment by MaartenGr** [comment]
Unfortunately, I have not seen this issue before. However, based on a quick search it seems that the culprit is typing which could be fixed by simply uninstalling it before installing BERTopic: `pip uninstall typing`. 

Let me know if this works!

**Comment by YukunYangNPF** [comment]
> Unfortunately, I have not seen this issue before. However, based on a quick search it seems that the culprit is typing which could be fixed by simply uninstalling it before installing BERTopic: `pip uninstall typing`.
> 
> Let me know if this works!

Thank you. It worked. Any thoughts on why that package will cause this problem?

**Comment by MaartenGr** [comment]
From what I could gather it seemed to be attributed to an incorrect install of that package. You can find more about that [here](https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry).
